### ISSUE TITLE
Missing project file in src directory

### ISSUE THREAD

**Issue by Zaid-Ajaj** [nojaf/fable-reactstrap#1]

**Comment by nojaf** [comment]
https://github.com/nojaf/fable-reactstrap/blob/master/src/Fable.Reactstrap.fsproj

**Comment by Zaid-Ajaj** [comment]
Was it already there 😱 looks like my Ctrl-F is broken...

**Comment by nojaf** [comment]
No, I just pushed some commits a few minutes ago.
Your eyes were not deceiving you, mea culpa.
