### ISSUE TITLE
fail to compile 

### ISSUE THREAD

**Issue by DerekLiang** [nojaf/fable-reactstrap#2]
here is the system information:
```
$ yarn --version
1.12.3
$ npm --version
6.9.0
$ dotnet --version
3.0.100-preview8-013656
```

Output for `yarn start`
```
...
ERROR in ./documentation/Entry.fsx
Module build failed (from ./node_modules/fable-loader/index.js):
Error: Exception of type 'FSharp.Compiler.CompileOps+FileNameNotResolved' was thrown.
    at Loader.command.then.data (C:\src\fable-reactstrap\node_modules\fable-loader\index.js:90:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Child html-webpack-plugin for "index.html":
...
```

**Comment by nojaf** [comment]
What Paket version are you using?
Do you have Paket as a global tool available? Does `yarn postinstall` run correctly?

**Comment by DerekLiang** [comment]
I tried on a different machine and it worked as expected. Thank you for your time.

**Comment by nojaf** [comment]
What is the difference on that machine? Dotnet cli version?

**Comment by DerekLiang** [comment]
Both are Windows. I am not sure. It could be dotnet version.
```
$ npm --version
6.4.1
$ yarn --version
1.14.0
$ dotnet --version
2.2.300
```

**Comment by UnoSD** [comment]
I am getting the same issue here, on both an existing and a new project from template (`dotnet new fable-elmish-react`). Completely different dotnet version (7.0.100), npm 8.19.2. Running on Arch Linux.

It sounds like it has nothing to do with this repository, so it makes sense to keep the issue closed, but any help would be appreciated. Thank you.
